/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_VO_MYREQObjectPageObjectPage journey");

        opaTest("Navigate to ZC_VO_MYREQObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheZC_VO_MYREQListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheZC_VO_MYREQListGenerated.onTable().iCheckRows();
            When.onTheZC_VO_MYREQListGenerated.onTable().iPressRow(0);

            Then.onTheZC_VO_MYREQObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheZC_VO_MYREQObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "HeaderFacet10" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "HeaderFacet20" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "HeaderFacet30" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "HeaderFacet40" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_VO_MYREQObjectPageGenerated.iCheckNumberOfSections(5);
            When.onTheZC_VO_MYREQObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheZC_VO_MYREQObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "SupplierName" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Uen" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "Email" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "ContactNumber" });
            When.onTheZC_VO_MYREQObjectPageGenerated.iPressSectionIconTabFilterButton("Address");
            Then.onTheZC_VO_MYREQObjectPageGenerated.iCheckSection({ section: "Address" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "Address" }).iCheckField({ property: "Street" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "Address" }).iCheckField({ property: "HouseNumber" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "Address" }).iCheckField({ property: "City" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "Address" }).iCheckField({ property: "PostalCode" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "Address" }).iCheckField({ property: "Region" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "Address" }).iCheckField({ property: "Country" });
            When.onTheZC_VO_MYREQObjectPageGenerated.iPressSectionIconTabFilterButton("Banks");
            Then.onTheZC_VO_MYREQObjectPageGenerated.iCheckSection({ section: "Banks" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onTable({ property: "_Bank" }).iCheckColumns(undefined, {"BankCity":{"header":"City"},"SwiftCode":{"header":"SWIFT Code"},"BankName":{"header":"Bank Name"},"AccountNumber":{"header":"Account Number"}});
            When.onTheZC_VO_MYREQObjectPageGenerated.iPressSectionIconTabFilterButton("CCodes");
            Then.onTheZC_VO_MYREQObjectPageGenerated.iCheckSection({ section: "CCodes" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onTable({ property: "_CompanyCode" }).iCheckColumns(undefined, {"CompanyCode":{"header":"CompanyCode"},"CompanyCodeName":{"header":"Company Name"}});
            When.onTheZC_VO_MYREQObjectPageGenerated.iPressSectionIconTabFilterButton("SupportingDocument");
            Then.onTheZC_VO_MYREQObjectPageGenerated.iCheckSection({ section: "SupportingDocument" });
            //When.onTheZC_VO_MYREQObjectPageGenerated.iGoToSection({ section: "SupportingDocument", subSection: "Attachment" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.iCheckSubSection({ section: "Attachment" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onTable({ property: "_Attachment" }).iCheckColumns(undefined, {"Content":{"header":"Attachment"},"FileName":{"header":"File Name"}});
            //When.onTheZC_VO_MYREQObjectPageGenerated.iGoToSection({ section: "SupportingDocument", subSection: "Declaration" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.iCheckSubSection({ section: "Declaration" });
            Then.onTheZC_VO_MYREQObjectPageGenerated.onForm({ section: "Declaration" }).iCheckField({ property: "AckConfirmed" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});